IMAGE_NAME = "bento/centos-stream-9"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox " do |v|
        v.allowlist_verified = true
        v.memory = 1024
        v.cpus = 1
	v.name = "Bastion"
    end

    config.vm.define "centos" do |centos|
        centos.vm.box = IMAGE_NAME
        centos.vm.network "forwarded_port", guest: 22, host: 2205, host_ip: "127.0.0.1"
	centos.vm.network "private_network", ip: "192.168.42.4", virtualbox__intnet: "intnet"
        centos.vm.hostname = "bastion"
    end

    # Install Ansible and Collection Grafana and Zabbix
    config.vm.provision "shell", path: "install-ansible-collection.sh"

end