IMAGE_NAME = "bento/ubuntu-24.04"

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox " do |v|
        v.allowlist_verified = true
        v.memory = 1024
        v.cpus = 1
	v.name = "Bastion"
    end

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = IMAGE_NAME
        ubuntu.vm.network "forwarded_port", guest: 22, host: 2205, host_ip: "127.0.0.1"
	ubuntu.vm.network "private_network", ip: "192.168.42.4", virtualbox__intnet: "intnet"
        ubuntu.vm.hostname = "bastion"
    end

    # Install Ansible and Collection Grafana and Zabbix
    config.vm.provision "shell", path: "install-ansible-collection.sh"

end