IMAGE_NAME = "bento/ubuntu-24.04"

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
        v.name = "Grafana-SRV02"
    end

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = IMAGE_NAME
        ubuntu.vm.network "forwarded_port", guest: 22, host: 2203, host_ip: "127.0.0.1"
	ubuntu.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"
        ubuntu.vm.network "private_network", ip: "192.168.42.3", virtualbox__intnet: "intnet"
        ubuntu.vm.hostname = "grafana"
    end

    config.vm.provision "file", source: "pre-install-docker.yml", destination: "~/"
    config.vm.provision "file", source: "docker-compose.yaml", destination: "~/"
    config.vm.provision "file", source: "install-zabbix-agent2.yml", destination: "~/"
    
    config.vm.provision "shell", inline: <<-SHELL
	sudo apt update
	sudo apt install -y ansible net-tools git
	sudo ansible-galaxy collection install community.zabbix --force
	sudo ansible-playbook install-zabbix-agent2.yml
	ansible-playbook pre-install-docker.yml
	sudo docker compose -f ./docker-compose.yaml up -d

    SHELL

end